namespace Cadmus.Core
{
    /// <summary>
    /// A filter eventually applied to <see cref="DataPin"/>'s generated by
    /// a part.
    /// </summary>
    public interface IDataPinFilter
    {
        /// <summary>
        /// Resets this filter inner state if any. This is called before
        /// enumerating a set of pins.
        /// </summary>
        void Reset();

        /// <summary>
        /// Applies this filter to the specified pin.
        /// </summary>
        /// <param name="pin">The pin.</param>
        /// <returns>False if the pin should be dropped; else true.</returns>
        bool Apply(DataPin pin);
    }
}
