//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadmus.Philology.Parts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cadmus.Philology.Parts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete operation must span at least 1 character.
        /// </summary>
        internal static string MspDeleteWithRal0 {
            get {
                return ResourceManager.GetString("MspDeleteWithRal0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete operation must not include a non zero B-value.
        /// </summary>
        internal static string MspDeleteWithVb {
            get {
                return ResourceManager.GetString("MspDeleteWithVb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert operation must include a non zero B-value.
        /// </summary>
        internal static string MspInsertWithoutVb {
            get {
                return ResourceManager.GetString("MspInsertWithoutVb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert operation must not span.
        /// </summary>
        internal static string MspInsertWithRalNon0 {
            get {
                return ResourceManager.GetString("MspInsertWithRalNon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert operation must not include an A-value.
        /// </summary>
        internal static string MspInsertWithVa {
            get {
                return ResourceManager.GetString("MspInsertWithVa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move operation must span at least 1 character.
        /// </summary>
        internal static string MspMoveWithRal0 {
            get {
                return ResourceManager.GetString("MspMoveWithRal0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move operation must not span across the B-value.
        /// </summary>
        internal static string MspMoveWithRblNon0 {
            get {
                return ResourceManager.GetString("MspMoveWithRblNon0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move operation must not include a non zero B-value.
        /// </summary>
        internal static string MspMoveWithVb {
            get {
                return ResourceManager.GetString("MspMoveWithVb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace operation must include a non zero B-value.
        /// </summary>
        internal static string MspReplaceWithoutVb {
            get {
                return ResourceManager.GetString("MspReplaceWithoutVb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace operation must span at least 1 character.
        /// </summary>
        internal static string MspReplaceWithRal0 {
            get {
                return ResourceManager.GetString("MspReplaceWithRal0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap operation must span at least 1 character across the A-value.
        /// </summary>
        internal static string MspSwapWithRal0 {
            get {
                return ResourceManager.GetString("MspSwapWithRal0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap operation must span at least 1 character across the B-value.
        /// </summary>
        internal static string MspSwapWithRbl0 {
            get {
                return ResourceManager.GetString("MspSwapWithRbl0", resourceCulture);
            }
        }
    }
}
